const ROUTES = {
    HOME: "/",
    CITY: "city/:slug",
    TRIP_DETAIL: "tripdetail",
    ABOUT: "about",
    EXPERIENCES: "experiences",
    EXPERIENCE_DETAIL: "experience/detail",
    EXPERIENCE_SLUG: "experience/:slug",
    ITINERARIES: "itineraries",
    ITINERARIES_DETAIL: "itineraries/detail",
    PAYMENT_TOUR: "payment/tour",
    EVENTS: "events",
    EVENTS_DETAIL: "events/detail",
    VISA_GUIDE: "visa-guide",
    ESSENTIALS: "essentials",
    GETTING_TO_AND_AROUND: "getting-to-and-around",
    ACCESSIBILITY: "accessibility",
    VIETNAM_PASS: "vietnam-pass",
    SAFETY: "safety",
    VISA_INFORMATION: "visainformation",
    PLACE_TO_GO: "placetogo",
    WEATHER_TRIP: "weathertrip",
    CURRENCY_GUIDE: "currency",
    DOWNLOAD_APP: "downloadapp",
    SEARCH_RESULT: "search-result/:keyword?",
    SIGNIN: "signin",
    SIGNUP: "signup",
    SIGNIN_PASSWORD: "signin-password",
    FORGOT_PASSWORD: "forgot-password",
    ATTRACTIONS: "attractions",
    SHOPPINGCART: "shopping",
    ATTRACTIONS_DETAIL: "AttractionsDetail",
    MAP_HANOI: "map-ha-noi",
    TRIP_DETAIL_RESULT: "tripdetail/result",
    NOT_FOUND: "*",
};

export default ROUTES;
