version: '3.8'

services:
  php:
    build:
      context: ./docker/php/${PHP_VERSION}
      args:
        COMPOSER_VERSION: ${COMPOSER_VERSION}
    restart: "always"
    ports:
      - "8080:8080"
    links:
      - database
    volumes:
      - .:/var/www/html
      - ./docker/php/${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini
  database:
    build:
      context: "./docker/database/${DATABASE_TYPE}/${DATABASE_VERSION}"
    restart: "always"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./docker/database/${DATABASE_TYPE}/${DATABASE_VERSION}/initdb:/docker-entrypoint-initdb.d
      - ./docker/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}